UseAltVoice: true
ResponseConfig:
  StartedTracking:
    - Text: |-
        <voice gender='female'>Hey {{User}}, I have something very important to tell you. Google Has dedicated 1 Billion Dollars to giving the world <break strength='weak'/> Wait, it seems like there's something even more important.
        This just in...  Aliens have landed on Mount Wayupthar. They have hidden items in Hyrule and Zebes and have been ordered by Ganon and Mother Brain, the leaders, to take over the two worlds.
        They have cpatured Shaktool, of Maridia, whoe has enough diabetes supplies to last 48 hours. Someone must save him and the world from these evil invaders.</voice>
      TrackerImage: female
      Weight: 1000
      AdditionalLines:
        - Text: Hello {{User}}. This sounds like a job for yours truly, CAPTAIN NOVOLIN!
          TrackerImage: default
  AutoTracker:
    GameStarted:
      - Text: <voice gender='female'>You need to check your blood sugar four times a day, but you can check it more often if you like. Don't forget to take the insulin dose I prescribed.</voice>
        TrackerImage: doctor
        Weight: 1000
    NearKraidsAwfulSon:
      - Text: <voice gender='female'>When traveling in Kraid's Lair, it's important to not look at Kraid's Awful Son.</voice>
        TrackerImage: doctor
        Weight: 1000
