UseAltVoice: true
ResponseConfig:
  StartedTracking:
    - Text: |-
        Hey {{User}}, I have something very important to tell you. Google Has dedicated 1 Billion Dollars to giving the world <break strength='weak'/> Wait, it seems like there's something even more important.
        This just in...  Aliens have landed on Mount Wayupthar. They have hidden items in Hyrule and Zebes and have been ordered by Ganon and Mother Brain, the leaders, to take over the two worlds.
        They have captured Shaktool, of Maridia, who has enough diabetes supplies to last 48 hours. Someone must save him and the world from these evil invaders.
      TrackerImage: alt
      Weight: 1000
      AdditionalLines:
        - Text: Hello {{User}}. This sounds like a job for yours truly, CAPTAIN NOVOLIN!
          TrackerImage: default
  AutoTracker:
    GameStarted:
      - Text: <voice gender='female'>You need to check your blood sugar four times a day, but you can check it more often if you like. Don't forget to take the insulin dose I prescribed.</voice>
        TrackerImage: doctor
        Weight: 1000
    NearKraidsAwfulSon:
      - Text: <voice gender='female'>When traveling in Kraid's Lair, it's important to not look at Kraid's Awful Son.</voice>
        TrackerImage: doctor
        Weight: 1000
    SkipSporeSpawn:
      - Text: <voice gender='female'>When playing S M Z 3, it's important to defeat Spore Spawn.</voice>
        TrackerImage: doctor
        Weight: 1000
  BeatGame:
    - Text: Congratulations, Captain. You saved the world from those evil aliens. I herby present to you the key to this seed.
      TrackerImage: alt
      Weight: 1000
  DungeonBossCleared:
    - Text: How does insulin lower your blood sugar level?<break time=500ms'/>It lets sugar out of your cells; or it lets sugar into your cells?
      TrackerImage: alt
      Weight: 500
    - Text: When does ketoacidosis happen?<break time=500ms'/>When blood sugars are very low,;when the body does not have enough insulin; or right after taking insulin?
      TrackerImage: alt
      Weight: 500
    - Text: Which helps prevent hypoglycemia?<break time=500ms'/>Sticking to your meal and activity plan; skipping a meal; not taking insulin; or none of these, because it can't be prevented?
      TrackerImage: alt
      Weight: 500
    - Text: When checking your feet, look for<break time=500ms'/>Dry skin; signs of rubbing from shoes; red or white places that are not always there; or all of these?
      TrackerImage: alt
      Weight: 500
    - Text: Where should unopened bottles of insulin be stored?<break time=500ms'/>In a hot, steamy place; in the freezer; or in the refrigerator?
      TrackerImage: alt
      Weight: 500
    - Text: When must insulin be taken?<break time=500ms'/>Every day at the times you and your doctor decide; once a week before breakfast; twice a month, at breakfast and bed; or Thursdays one third hour before eating
      TrackerImage: alt
      Weight: 500
    - Text: Why is it good to try to stay in your B G target range?<break time=500ms'/>Because it makes your parents and doctors happy; because otherwise you are weird; or because it helps you stay healthy
      TrackerImage: alt
      Weight: 500
    - Text: How does glucagon make your BG go up so fast?<break time=500ms'/>It is super sugar, so your BG goes up; it causes your body to make glucose really fast; it stops insulin from working.
      TrackerImage: alt
      Weight: 500
LocationConfig:
  # Old Man
  - LocationNumber: 259
    OutOfLogic:
      - Text: "Whew, what a hike. Hi, old man in the cave. I am looking for the shaktool. But just in case I get into some trouble, I want to let you know that I have diabetes"
        Weight: 1000
        AdditionalLines:
          - Text: <prosody volume='silent'>a</prosody><break time="5s"/>
            TrackerImage: blank
          - Text: Thanks. In case of an emergency, rangers will know you have diabetes and will have a good idea how to help you. Take care, Captain Novolin.
            TrackerImage: oldman
    WhenTrackingJunk:
      - Text: "Whew, what a hike. Hi, old man in the cave. I am looking for the shaktool. But just in case I get into some trouble, I want to let you know that I have diabetes"
        Weight: 1000
        AdditionalLines:
          - Text: <prosody volume='silent'>a</prosody><break time="5s"/>
            TrackerImage: blank
          - Text: Thanks. In case of an emergency, rangers will know you have diabetes and will have a good idea how to help you. Take care, Captain Novolin.
            TrackerImage: oldman
    WhenTrackingProgression:
      - Text: "Whew, what a hike. Hi, old man in the cave. I am looking for the shaktool. But just in case I get into some trouble, I want to let you know that I have diabetes"
        Weight: 1000
        AdditionalLines:
          - Text: <prosody volume='silent'>a</prosody><break time="5s"/>
            TrackerImage: blank
          - Text: Thanks. In case of an emergency, rangers will know you have diabetes and will have a good idea how to help you. Take care, Captain Novolin.
            TrackerImage: oldman
  # Sanctuary
  - LocationNumber: 347
    OutOfLogic:
      - Text: "Hello Zelda. I have diabetes. Is there anything special I should know before playing this seed?"
        Weight: 1000
        AdditionalLines:
          - Text: "<voice gender='female'>Thanks for telling me. The most important thing to remember is that extra activity can cause your blood sugars to go lower than regular activity. Be sure to take some extra snacks with you. And have fun.</voice>"
            TrackerImage: zelda
    WhenTrackingJunk:
      - Text: "Hello Zelda. I have diabetes. Is there anything special I should know before playing this seed?"
        Weight: 1000
        AdditionalLines:
          - Text: "<voice gender='female'>Thanks for telling me. The most important thing to remember is that extra activity can cause your blood sugars to go lower than regular activity. Be sure to take some extra snacks with you. And have fun.</voice>"
            TrackerImage: zelda
    WhenTrackingProgression:
      - Text: "Hello Zelda. I have diabetes. Is there anything special I should know before playing this seed?"
        Weight: 1000
        AdditionalLines:
          - Text: "<voice gender='female'>Thanks for telling me. The most important thing to remember is that extra activity can cause your blood sugars to go lower than regular activity. Be sure to take some extra snacks with you. And have fun.</voice>"
            TrackerImage: zelda
ItemConfig:
  - Item: Pegasus Boots
    WhenTracked:
      "1":
        - Text: Check you feet. They have boots now.
          Weight: 1000
  - Item: Hi-Jump Boots
    WhenTracked:
      "1":
        - Text: Excuse me Captain Novolin. Could I give you a bit of advice?
          Weight: 1000
          TrackerImage: flipped
          AdditionalLines:
            - Text: Why sure, Joe.
            - Text: You should wear sturdy shoes and socks to protect your feet throughout your adventure. Here, take these. I think they will fit just fine.
              TrackerImage: flipped
            - Text: Thanks for the shoes Joe. I'll be sure to wear them.
  - Item: Power Bomb
    WhenTracked:
      "1":
        - Text: "In your breakfast meal plan you could have: 5 borgers"
          Weight: 1000
          TrackerImage: nutritionist
      "2":
        - Text: "For a morning snack you could have: 10 burgs"
          Weight: 1000
          TrackerImage: nutritionist
      "3":
      "4":
        - Text: "For lunch you could have: {0} burgers"
          Weight: 1000
          TrackerImage: nutritionist
      "5":
        - Text: "For an afternoon snack you could have: {0} borgers"
          Weight: 1000
          TrackerImage: nutritionist
      "8":
        - Text: "Yum... enjoy your dinner: {0} powerful borgers"
          Weight: 1000
          TrackerImage: nutritionist
      "9":
        - Text: "Before bed tonight have: {0} powerful borgers"
          Weight: 1000
          TrackerImage: nutritionist
      "10":
        - Text: "<voice gender='female'>As your doctor, I must ask that you please stop eating so many burgers.</voice>"
          Weight: 1000
          TrackerImage: doctor
